# Generated by Django 4.1.7 on 2023-05-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('phone', models.SmallIntegerField(max_length=20)),
                ('aboutMe', models.TextField(max_length=2500)),
                ('characteristics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CVMakerApp.characteristic')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CVMakerApp.education')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CVMakerApp.experience')),
                ('languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CVMakerApp.language')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CVMakerApp.skill')),
            ],
        ),
    ]
